services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: workshop
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql